name: Build and Publish Storybook to GH Pages

on:
  push:
    branches:
      - master
    paths: ["svg/**"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: build-publish
        uses: bitovi/github-actions-react-to-ghp@v1.2.1
        with:
          path: storybook-static
          build_command: npm run build-storybook
